// Heroicons (Outline) - Toutes les icônes disponibles
import {
    HomeIcon,
    FolderIcon,
    DocumentIcon,
    UsersIcon,
    UserGroupIcon,
    LinkIcon,
    ChartBarIcon,
    Cog6ToothIcon,
    Squares2X2Icon,
    PlusIcon,
    ArrowUpIcon,
    ArrowDownIcon,
    ArrowRightIcon,
    CheckIcon,
    XMarkIcon,
    ExclamationTriangleIcon,
    InformationCircleIcon,
    MagnifyingGlassIcon,
    BellIcon,
    UserCircleIcon,
    PhotoIcon,
    VideoCameraIcon,
    DocumentTextIcon,
    CloudArrowUpIcon,
    TrashIcon,
    PencilIcon,
    EyeIcon,
    HeartIcon,
    ChatBubbleLeftIcon,
    ShareIcon,
    ArrowDownTrayIcon,
    ArrowLeftIcon,
    CalendarIcon,
    ClockIcon,
    UserIcon,
    EnvelopeIcon,
    LockClosedIcon,
    GlobeAltIcon,
    ShieldCheckIcon,
    SparklesIcon,
    PlayIcon,
    FolderPlusIcon,
    FunnelIcon,      // FilterIcon → FunnelIcon
    UserPlusIcon,
    UserMinusIcon,
    DocumentDuplicateIcon, // CopyIcon → DocumentDuplicateIcon
    EyeSlashIcon,    // EyeOffIcon → EyeSlashIcon
    ArrowPathIcon,
    CreditCardIcon,
    ArrowUpRightIcon,
    FolderOpenIcon,
    StarIcon,
    PaperAirplaneIcon,
    PaperClipIcon,
} from '@heroicons/react/24/outline';

// Heroicons (Solid)
import {
    HomeIcon as HomeIconSolid,
    FolderIcon as FolderIconSolid,
    DocumentIcon as DocumentIconSolid,
    UsersIcon as UsersIconSolid,
    UserGroupIcon as UserGroupIconSolid,
    LinkIcon as LinkIconSolid,
    ChartBarIcon as ChartBarIconSolid,
    Cog6ToothIcon as Cog6ToothIconSolid,
    CheckIcon as CheckIconSolid,
    HeartIcon as HeartIconSolid,
    StarIcon as StarIconSolid,
    EnvelopeIcon as EnvelopeIconSolid,
    FunnelIcon as FunnelIconSolid,
} from '@heroicons/react/24/solid';

// Lucide Icons
import {
    LayoutDashboard,
    Briefcase,
    Cloud,
    Database,
    Calendar,
    Clock,
    Upload,
    Download,
    FolderOpen as FolderOpenLucide,
    FileImage,
    FileVideo,
    FileText,
    File,
    Users,
    UserPlus,
    UserMinus,
    Settings,
    LogOut,
    Menu,
    Search,
    Filter,
    MoreHorizontal,
    MoreVertical,
    Star,
    MessageSquare,
    Send,
    Paperclip,
    Link as LinkIcon2,
    Lock,
    Unlock,
    Globe,
    Eye,
    EyeOff,
    Edit,
    Trash2,
    Plus,
    Minus,
    X,
    Check,
    AlertCircle,
    Info,
    HelpCircle,
    Loader2,
    RefreshCw,
    ChevronDown,
    ChevronRight,
    ChevronLeft,
    ChevronUp,
    ChevronsUpDown,
    Shield,
    Sparkles,
    Play,
    FolderPlus,
    UserCircle,
    CreditCard,
    ArrowUpRight,
    ArrowDownToLine,
    Mail,
    Lock as LockIcon,
    Copy,
    EyeOff as EyeOffIcon,
} from 'lucide-react';

// Exports - Heroicons Outline
export {
    HomeIcon,
    FolderIcon,
    DocumentIcon,
    UsersIcon,
    UserGroupIcon,
    LinkIcon,
    ChartBarIcon,
    Cog6ToothIcon,
    Squares2X2Icon,
    PlusIcon,
    ArrowUpIcon,
    ArrowDownIcon,
    ArrowRightIcon,
    CheckIcon,
    XMarkIcon,
    ExclamationTriangleIcon,
    InformationCircleIcon,
    MagnifyingGlassIcon,
    BellIcon,
    UserCircleIcon,
    PhotoIcon,
    VideoCameraIcon,
    DocumentTextIcon,
    CloudArrowUpIcon,
    TrashIcon,
    PencilIcon,
    EyeIcon,
    HeartIcon,
    ChatBubbleLeftIcon,
    ShareIcon,
    ArrowDownTrayIcon,
    ArrowLeftIcon,
    CalendarIcon,
    ClockIcon,
    UserIcon,
    EnvelopeIcon,
    LockClosedIcon,
    GlobeAltIcon,
    ShieldCheckIcon,
    SparklesIcon,
    PlayIcon,
    FolderPlusIcon,
    FunnelIcon,
    UserPlusIcon,
    UserMinusIcon,
    DocumentDuplicateIcon,
    EyeSlashIcon,
    ArrowPathIcon,
    CreditCardIcon,
    ArrowUpRightIcon,
    FolderOpenIcon,
    StarIcon,
    PaperAirplaneIcon,
    PaperClipIcon,
};

// Exports - Heroicons Solid
export {
    HomeIconSolid,
    FolderIconSolid,
    DocumentIconSolid,
    UsersIconSolid,
    UserGroupIconSolid,
    LinkIconSolid,
    ChartBarIconSolid,
    Cog6ToothIconSolid,
    CheckIconSolid,
    HeartIconSolid,
    StarIconSolid,
    EnvelopeIconSolid,
    FunnelIconSolid,
};

// Exports - Lucide (pour les icônes qui n'existent pas dans Heroicons)
export {
    LayoutDashboard,
    Briefcase,
    Cloud,
    Database,
    Calendar,
    Clock,
    Upload,
    Download,
    FolderOpenLucide,
    FileImage,
    FileVideo,
    FileText,
    File,
    Users,
    UserPlus,
    UserMinus,
    Settings,
    LogOut,
    Menu,
    Search,
    Filter,
    Filter as FilterIcon,
    MoreHorizontal,
    MoreVertical,
    Star,
    MessageSquare,
    Send,
    Paperclip,
    LinkIcon2,
    Lock,
    Unlock,
    Globe,
    Eye,
    EyeOff,
    Edit,
    Trash2,
    Plus,
    Minus,
    X,
    X as XIcon,
    Check,
    Cloud as CloudIcon,
    Copy as CopyIcon,
    AlertCircle,
    Info,
    HelpCircle,
    Loader2,
    RefreshCw,
    ChevronDown,
    ChevronDown as ChevronDownIcon,
    ChevronRight,
    ChevronLeft,
    ChevronUp,
    ChevronsUpDown,
    Shield,
    Sparkles,
    Play,
    FolderPlus,
    UserCircle,
    CreditCard,
    ArrowUpRight,
    ArrowDownToLine,
    Mail,
    Mail as MailIcon,
    LockIcon,
    Copy,
    EyeOffIcon,
};